### ISSUE TITLE
Texts are treated as sequential blocking requests without async queueing

### ISSUE THREAD

**Issue by jerinphilip** [browsermt/bergamot-translator#35]
Scouring through bergamot-translator-extension sources, it seems that browser team is trying to break texts into sentences and provide them as individual requests. This can lead to a significant slowdown, referred to in the extension's [release docs](https://github.com/mozilla-extensions/bergamot-browser-extension/releases/tag/v0.2.0).

> Translation speeds are temporarily low - about 150-200 words per second instead of expected 500-600 words per second

No threads/async prevents any of `marian::bergamot::Service`s request collect and pack batches efficiently mechanism, as long as in the current state of unified API's specification. There are potentially two solutions in my mind, enable threading/async queuing mechanisms or collect it as one string and do the processing somewhere in TranslationModel.

https://github.com/browsermt/bergamot-translator/blob/51f702ea6c849687488d6478b3bc428f0ad033ae/src/translator/TranslationModel.cpp#L60-L64

Opening the issue for discussion.
/cc @abhi-agg @motin

**Comment by abhi-agg** [comment]
@jerinphilip We are breaking text into sentences because in current integration, the current ssplit-cpp (with pcre compiled from sources) doesn't split sentences.

Of course, we will send the blob of text as soon as I make ssplit-cpp functional (with pcre2 compiled from sources).

Re: No threads/async
We have already discussed that once we start working on making threads working for wasm, we will enable async requests as well.

**Comment by abhi-agg** [comment]
@jerinphilip No more of breaking text into sentences [via this commit](https://github.com/browsermt/bergamot-translator/commit/462a850d8ae554e835f0e3e64aef897aa3f93dad). So this is resolved.

I am closing this issue.

**Comment by kpu** [comment]
The subject line of the issue is "Texts are treated as sequential blocking requests without async queueing".  That's still a problem right?

**Comment by abhi-agg** [comment]
As I said, once we start working on making threads work for wasm, we can enable async requests as well.

I don't mind keeping this issue open and resolve it once we make threads to work 👍

**Comment by jerinphilip** [comment]
There is a workaround for this currently implemented in a draft PR.

https://github.com/browsermt/bergamot-translator/blob/32285aafb2a0815e730615d74c64625b1fb52008/src/translator/service.cpp#L125-L155
